import 'package:flutter/material.dart';

const Color kPrimaryColor = Colors.green;
const Color iconColor = Colors.white;


const List<String> stateList = ['1', '2', '3', '4','5','6','7'];
const List<String> districtList =[
  'Taplejung',
   'Phidim',
  'Ilam',
  'Chandragadi',
  'Morang',
  'Inaruwa',
  'Dhankutta',
  'Khandbari',
  'Bhojpur',
  'Terhathum',
  'Okhaldunga',
  'Diktel',
  'Solusalleri',
  'Gaighat',
  'Rajbiraj',
  'Siraha',
  'Dhanusa',
  'Jaleswor',
  'Malangwa',
  'Sindhuligadi',
  'Manthali',
  'Charikot',
  'Sindhupalchauk',
  'Dhulikhel',
  'Lalitpur',
  'Bhaktapur',
  'Kathmandu',
  'Bidur',
  'Dhunche',
  'Dhadingbeshi',
  'Makwanpur',
  'Gaur',
  'Kalaiya',
  'Birgunj',
  'Bharatpur',
  'Gorkha',
  'Beshisahar',
  'Damauli',
  'Putalikhel',
  'Pokhara',
  'Chame',
  'Mustang',
  'Kusma',
  'Baini',
  'Baglung',
  'Gulmi',
  'Tansen',
  'Tansen',
  'Parasi',
  'Bhairawa',
  'Sandhikarka',
  'Taulihawa',
  'Pyuthan',
  'Libang',
  'Musikot',
  'Muskikot',
  'Salyan',
  'Ghorahi',
  'Bardiya',
  'Birendranagar',
  'Nepalgunj',
  'Jajarkot',
  'Dolpa',
  'Simikot',
  'Manma',
  'Gamgadi',
  'Jumla',
  'Bajura',
  'Chainpur',
  'Mangalsen',
  'Silgadi',
  'Dhangadi',
  'Kanchanpur',
  'Dadeldhura',
  'Baitadi',
  'Darchula'
];